# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  repositories:
    - repository: PrimeService   # Name used during the checkout step
      type: Github
      endpoint: MattSheehanDev    # Service Connection name
      name: dotnet/samples

pool:
  vmImage: windows-latest


stages:
  - stage: BuildApp
    displayName: Build App
    jobs:
      - job: BuildPrimeService
        steps:
          - checkout: PrimeService
          - task: DotNetCoreCLI@2
            displayName: Build PrimeService
            inputs:
              command: 'build'
              projects: |
                core/getting-started/unit-testing-using-dotnet-test/PrimeService/PrimeService.csproj
                core/getting-started/unit-testing-using-dotnet-test/PrimeService.Tests/PrimeService.Tests.csproj
          - task: DotNetCoreCLI@2
            displayName: Test PrimeService
            inputs:
              command: 'test'
              projects: 'core/getting-started/unit-testing-using-dotnet-test/PrimeService.Tests/PrimeService.Tests.csproj'
              arguments: '--no-restore --no-build'
              publishTestResults: true

  # - stage: DeployToStaging
  #   dependsOn: BuildApp
  #   jobs:
  #     - deployment: 

  # - stage: DeployToProduction
  #   dependsOn: BuildApp


# steps:
# - checkout: PrimeServices
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
