trigger:
  branches:
  - master
  paths:
  - azure-pipeline-deploy.yml

resources:
  repositories:
    - repository: dotnet-core-api   # Name used during the checkout step
      type: Github
      endpoint: MattSheehanDev      # Service Connection name
      name: Azure-Samples/dotnet-core-api

pool:
  vmImage: windows-latest

stages:
  - stage: BuildApp
    displayName: Build App
    jobs:
      - job: BuildApi
        steps:
          - checkout: dotnet-core-api
          - task: DotNetCoreCLI@2
            displayName: Build dotnet-core-api
            inputs:
              command: 'build'
              projects: 'TodoApi.csproj'
              arguments: '-o $(Build.ArtifactStagingDirectory)'
          - publish: '$(Build.ArtifactStagingDirectory)'
            artifact: api

  # - stage: DeployApp
  #   displayName: Deploy App
  #   dependsOn: BuildApp
  #   jobs:
  #     - deployment: DeployApi
  #       displayName: Deploy dotnet-core-api
  #       environment: staging-api
  #       strategy:
  #         runOnce:
  #           deploy:
  #             steps:
  #             - download: current
        



  # - stage: DeployToStaging
  #   dependsOn: BuildApp
  #   jobs:
  #     - deployment: 

  # - stage: DeployToProduction
  #   dependsOn: BuildApp


# steps:
# - checkout: PrimeServices
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
