trigger:
  branches:
    include:
      - master
  paths:
    include:
      - pipeline-copy-files.yml

resources:
  repositories:
    - repository: CppExample          # Name used during the checkout step
      type: Github
      endpoint: MattSheehanDev        # Service Connection name
      name: memsharded/hello
 
stages:
  - stage: BuildCpp
    displayName: Build Cpp Example
    jobs:
    - job: Build
      pool:
        vmImage: 'windows-latest'
      steps:
      - checkout: CppExample
      
      - task: AzurePowerShell@5
        inputs:
          azureSubscription: CodeMash2022-sp
          azurePowerShellVersion: LatestVersion
          ScriptType: InlineScript
          inline: |
            mkdir build
            cd build
        
      - task: CMake@1
        displayName: 'CMake ..'
        inputs:
          cmakeArgs: '..'

      - task: CMake@1
        displayName: 'CMake --build . --config Debug'
        inputs:
          cmakeArgs: '--build . --config Debug'

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: '**/bin/*.exe'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - publish: '$(Build.ArtifactStagingDirectory)'
        artifact: build
