trigger:
  branches:
    include:
      - master
  paths:
   include:
     - pipeline-deploy-complete.yml

resources:
  repositories:
    - repository: dotnet-core-api   # Name used during the checkout step
      type: Github
      endpoint: MattSheehanDev      # Service Connection name
      name: CodeMazeBlog/unit-testing-aspnetcore-webapi

pool:
  vmImage: windows-latest

stages:
  - stage: Build
    jobs:
      - job: Publish
        steps:
          - checkout: dotnet-core-api
          - task: DotNetCoreCLI@2
            displayName: Build dotnet-core-api
            inputs:
              command: 'publish'
              projects: 'netcore-unit-testing/web-api/web-api/web-api.csproj'
              arguments: '-o $(Build.ArtifactStagingDirectory)'
          - publish: '$(Build.ArtifactStagingDirectory)'
            artifact: api

  - stage: DeployAppServiceOne
    displayName: Deploy Environment 1
    dependsOn: PublishApp
    jobs:
        # Deployment jobs are a special kind of job that can
        # record deployment history and deployment strategy.
        # They do not automatically clone the source repo.
      - deployment: DeployApi
        displayName: Deploy app service
        environment: env-one
        strategy:
          runOnce:
            # Deploy hooks download artifacts automatically
            deploy:
              steps:
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  WebAppKind: 'webApp'
                  WebAppName: 'api-app-east'
                  ResourceGroupName: 'artifacts-rg'
                  Package: '$(Agent.BuildDirectory)/**/*.zip'
                  ConnectedServiceName: CodeMash2022-sp

  - stage: DeployAppServiceTwo
    displayName: Deploy Environment 2
    dependsOn: PublishApp
    jobs:
      - deployment: DeployApi
        displayName: Deploy app service
        environment: env-two
        strategy:
          runOnce:
            deploy:
              steps:
                # The download keywork is a shortcut for
                # the task DownloadPipelineArtifact.
                # It also overrides the default behavior of
                # downloading all pipeline artifacts.
              - download: current
                artifact: api
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  WebAppKind: 'webApp'
                  WebAppName: 'api-app-east2'
                  ResourceGroupName: 'artifacts-rg'
                  Package: '$(Agent.BuildDirectory)/**/*.zip'
                  ConnectedServiceName: CodeMash2022-sp

