trigger:
  branches:
    include:
      - master
  paths:
   include:
     - pipeline-npm-cache.yml

resources:
  repositories:
    - repository: nodejs-example    # Name used during the checkout step
      type: Github
      endpoint: MattSheehanDev      # Service Connection name
      name: gothinkster/node-express-realworld-example-app

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Yarn
    jobs:
      - job: YarnInstall
        displayName: Yarn Install
        steps:
          - checkout: nodejs-example
          
          - task: Cache@2
            displayName: Cache Yarn packages
            inputs:
              path: $(Pipeline.Workspace)/.yarn
              key: '"yarn" | "$(Agent.OS)" | yarn.lock'
              restoreKeys: |
                yarn | "$(Agent.OS)"
                yarn

          - script: yarn --frozen-lockfile
